"""crear tabla monthly_incomes

Revision ID: 589dc34456b6
Revises: b6afe98d5835
Create Date: 2026-08-07 12:11:08.903918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589dc34456b6'
down_revision: Union[str, Sequence[str], None] = 'b6afe98d5835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_incomes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('income_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'year', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_incomes')
    # ### end Alembic commands ###
